# Generated by Django 3.1 on 2020-08-31 04:28

from django.db import migrations, models
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='upload_images',
            field=models.FileField(blank=True, null=True, upload_to=notice.models.get_file_path, verbose_name='이미지파일'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
